### ISSUE TITLE
Enable model registration and scoring for classification models

### ISSUE THREAD

**Issue by JacopoTeneggi** [microsoft/InnerEye-DeepLearning#398]
After the run is successfully completed, I see a `.tar` archive named `50_checkpoint.pth.tar` in `outputs/checkpoints` under the _"Outputs & Logs"_ tab, but I do not see the model under the _"Models"_ tab.

As mentioned in the [docs](https://github.com/microsoft/InnerEye-DeepLearning/blob/main/docs/deploy_on_aml.md) no clear pipeline is defined for classification models. 

How can I run a trained model on AML without a `score.py` file?

[AB#3920](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/3920)

**Comment by ant0nsc** [comment]
One of the conceptual difficulties for classification models is their (potentially) very complex input. We have designed the classification models such that you can feed in a combination of image and non-image features - to use that at inference time in all its generality, you need to feed in a folder with a mini mock dataset for the test data. 

We have not yet had a use case for that, hence it is not in the toolbox.

If you'd like to help extend the toolbox here, the necessary steps are:
- Extend the model registration code [here](https://github.com/microsoft/InnerEye-DeepLearning/blob/cc96b620c1e10a4f858568c98a03b6b701bb6005/InnerEye/ML/run_ml.py#L405) to also register classification models
- Model registration for classification models is almost identical to that for segmentation models. The only piece of code that is in the way is [copy_child_paths](https://github.com/microsoft/InnerEye-DeepLearning/blob/cc96b620c1e10a4f858568c98a03b6b701bb6005/InnerEye/ML/run_ml.py#L545), where we create an object that is specific to segmentation models. #366 is already removing those offending fields, and I would expect that we can use the same model registration code for segmentation and classification models after.
- Extend `score.py` to deal with models that are not segmentation models. This code would require quite a bit of cleanup, because it contains quite a bit of logic that, in my view, should actually live inside the models, and not in a scoring script.

The first 2 steps should be relatively simple. Once you have that, you can download a trained model from AzureML, read out the checkpoint, and do pretty much anything with it, without having to rely on fancy `score.py`

**Comment by ant0nsc** [comment]
Classification models are registered now, see #455. We do not yet have a clear story for running those with score.py.
